using UnityEngine;

namespace Nimrita.InstaReload
{
    /// <summary>
    /// Companion fixture for TEST 4 in TestInstaReload.
    ///
    /// DO NOT EDIT THIS FILE DURING THE TESTS. That is the entire point of it.
    ///
    /// InstaReload compiles one file at a time. When TestInstaReload.cs is edited and
    /// reloaded, THIS file is not recompiled, so its call to SharedHelper() still points at
    /// the original method in memory.
    ///
    /// That is what makes TEST 4 meaningful: it proves that deleting a method cannot crash
    /// an unpatched caller (the method is still there), while also showing the honest cost —
    /// that caller keeps running the OLD implementation until Play Mode ends.
    ///
    /// Attach this to the SAME GameObject as TestInstaReload.
    /// </summary>
    public sealed class TestInstaReloadCaller : MonoBehaviour
    {
        private TestInstaReload _target;
        private float timer;

        private void Awake()
        {
            _target = GetComponent<TestInstaReload>();
            if (_target == null)
            {
                Debug.LogWarning("[Test] TestInstaReloadCaller needs TestInstaReload on the same GameObject.");
                return;
            }

            Debug.Log("[Test] TestInstaReloadCaller ACTIVE — TEST 4 will be exercised.");
        }

        private void Update()
        {
            if (_target == null)
            {
                return;
            }

            timer += Time.deltaTime;
            if (timer < 1.0f)
            {
                return;
            }

            timer = 0f;
            _target.SharedHelper();
        }
    }
}
